(* ================================================================= #
 *                         GRAMMAR SPECIFICATION                     *
 *                              Version 0.0                          *
 * ================================================================= *)

SourceUnit ::= Shebang? TopLevelElement* EOF ;

TopLevelElement
    ::= DeclareStmt
      | NamespaceDecl
      | ImportDirective
      | TypeDeclStmt
      | OpaqueTypeDeclStmt
      | StructDeclStmt
      | ClassLikeDecl
      | FunctionDecl
      | ConstDecl
      | ExternDecl
      | HaltCompilerStmt
      | Statement ;

(* ----------------------------------------------------------------- *
 *                        DIRECTIVES & NAMESPACES                    *
 * ----------------------------------------------------------------- *)

DeclareStmt ::= "declare" "(" DeclareDirectiveList ")" Term ;
DeclareDirectiveList ::= DeclareDirective ( "," DeclareDirective )* ","? ;
DeclareDirective ::= Identifier "=" ScalarLiteral ;

NamespaceDecl
    ::= "namespace" QualifiedName Term
      | "namespace" QualifiedName Block ;

ImportDirective
    ::= "use" ImportKind? UseClauseList Term
      | "use" ImportKind? QualifiedName "{" ImportGroupList "}" Term
      | "use" ImportKind? "{" ImportGroupList "}" ( "from" QualifiedName )? Term ;

ImportKind ::= "function" | "const" | "type" ;

UseClauseList ::= UseClause ( "," UseClause )* ","? ;
UseClause ::= QualifiedName ( "as" Identifier )? ;

ImportGroupList ::= ImportGroup ( "," ImportGroup )* ","? ;
ImportGroup ::= QualifiedName ( "as" Identifier )? ;

(* ----------------------------------------------------------------- *
 *                       OTY TYPE DECLARATIONS                       *
 * ----------------------------------------------------------------- *)

TypeDeclStmt
    ::= "type" Identifier TypeParameters? "=" TypeExpr Term ;

OpaqueTypeDeclStmt
    ::= "opaque" "type" Identifier TypeParameters? ( "extends" TypeExpr )? "=" TypeExpr Term ;

StructDeclStmt
    ::= Attributes? StructModifiers? "struct" Identifier TypeParameters?
        StructExtends? StructImplements? StructBody ;

StructModifiers ::= "readonly" ;
StructExtends ::= "extends" QualifiedName ;
StructImplements ::= "implements" TypeList ;

(* ----------------------------------------------------------------- *
 *                       CLASS-LIKE DECLARATIONS                     *
 * ----------------------------------------------------------------- *)

ClassLikeDecl
    ::= ClassDecl
      | InterfaceDecl
      | TraitDecl
      | EnumDecl ;

ClassDecl
    ::= Attributes? ClassModifiers? "class" Identifier TypeParameters?
        ClassExtends? ClassImplements? ClassBody ;

ClassExtends ::= "extends" QualifiedName GenericArguments? ;
ClassImplements ::= "implements" TypeList ;

InterfaceDecl
    ::= Attributes? InterfaceModifiers? "interface" Identifier TypeParameters?
        InterfaceExtends? InterfaceBody ;

InterfaceModifiers ::= "readonly" ;
InterfaceExtends ::= "extends" TypeList ;

TraitDecl
    ::= Attributes? "trait" Identifier TypeParameters? TraitBody ;

EnumDecl
    ::= Attributes? "enum" Identifier EnumBackingType?
        EnumImplements? EnumBody ;

EnumBackingType ::= ":" ( "int" | "string" ) ;
EnumImplements ::= "implements" TypeList ;

ClassBody ::= "{" ClassMember* "}" ;
InterfaceBody ::= "{" InterfaceMember* "}" ;
TraitBody ::= "{" TraitMember* "}" ;
EnumBody ::= "{" EnumMember* "}" ;
StructBody ::= "{" StructMember* "}" ;

ClassMember
    ::= PropertyDecl
      | MethodDecl
      | ConstDecl
      | UseTrait
      | RequireStmt
      | ClassEnumCase ;

InterfaceMember
    ::= InterfaceMethodDecl
      | InterfaceConstDecl
      | InterfacePropertyDecl
      | RequireStmt ;

TraitMember
    ::= PropertyDecl
      | MethodDecl
      | ConstDecl
      | UseTrait
      | RequireStmt ;

StructMember ::= StructFieldDecl ;

EnumMember
    ::= EnumCase
      | MethodDecl
      | ConstDecl
      | UseTrait ;

ClassEnumCase ::= EnumCase ;

EnumCase
    ::= Attributes? "case" Identifier ( "=" Expression )? Term ;

RequireStmt
    ::= "require" "extends" QualifiedName Term
      | "require" "implements" QualifiedNameList Term ;

UseTrait
    ::= "use" QualifiedNameList TraitAdaptations? Term ;

QualifiedNameList ::= QualifiedName ( "," QualifiedName )* ","? ;

TraitAdaptations ::= "{" TraitAdaptation* "}" ;

TraitAdaptation
    ::= QualifiedName "::" Identifier "insteadof" QualifiedNameList Term
      | QualifiedName ( "::" Identifier )? "as" VisibilityModifier? Identifier? Term ;

(* ----------------------------------------------------------------- *
 *                      FUNCTIONS & MEMBERS                          *
 * ----------------------------------------------------------------- *)

FunctionDecl
    ::= Attributes? FunctionModifiers? FunctionKeyword "&"? Identifier
        TypeParameters? "(" ParameterList? ")" ReturnTypeClause? Block ;

MethodDecl
    ::= Attributes? MethodModifiers? FunctionKeyword "&"? Identifier
        TypeParameters? "(" ParameterList? ")" ReturnTypeClause?
        ( Block | Term ) ;

InterfaceMethodDecl
    ::= Attributes? MethodModifiers? FunctionKeyword "&"? Identifier
        TypeParameters? "(" ParameterList? ")" ReturnTypeClause? Term ;

FunctionKeyword ::= "function" | "fn" ;

FunctionModifiers ::= FunctionModifier* ;
MethodModifiers ::= MethodModifier* ;

FunctionModifier ::= "public" | "protected" | "private" | "abstract" | "final" | "static" ;
MethodModifier   ::= "public" | "protected" | "private" | "abstract" | "final" | "static" ;

ClassModifiers ::= ClassModifier* ;
ClassModifier ::= "abstract" | "final" | "readonly" ;

ParameterList ::= Parameter ( "," Parameter )* ","? ;

Parameter
    ::= Attributes? ParameterModifiers? TypeExpr? "&"? "..."?
        VariableName ( "=" Expression )? ;

ParameterModifiers ::= VisibilityModifier? "readonly"? ;
VisibilityModifier ::= "public" | "protected" | "private" ;

(* Property Declarations with PHP 8.4 Property Hooks Support *)
PropertyDecl
    ::= Attributes? PropertyModifiers TypeExpr? PropertyItem
        ( "," PropertyItem )* PropertySuffix ;

PropertyModifiers ::= VisibilityModifier? "static"? "readonly"? ;
PropertyItem ::= VariableName ( "=" Expression )? ;
PropertySuffix ::= Term | AccessorBlock ;

AccessorBlock ::= "{" Accessor* "}" ;
Accessor
    ::= Attributes? "get" AccessorBody
      | Attributes? "set" "(" Parameter? ")" AccessorBody ;

AccessorBody ::= "=>" Expression Term | Block | Term ;

InterfacePropertyDecl
    ::= Attributes? VisibilityModifier? "readonly"? TypeExpr VariableName Term ;

ConstDecl
    ::= Attributes? VisibilityModifier? "const" ConstItem
        ( "," ConstItem )* Term ;

InterfaceConstDecl
    ::= Attributes? VisibilityModifier? "const" ConstItem
        ( "," ConstItem )* Term ;

ConstItem ::= Identifier ( ":" TypeExpr )? "=" Expression ;

VarDeclStmt ::= VariableDeclarationList Term ;

VariableDeclarationList ::= VariableDeclaration ( "," VariableDeclaration )* ","? ;

VariableDeclaration ::= TypeExpr? VariableName ( "=" Expression )? ;

ExternDecl ::= "extern" ExternTarget ;

ExternTarget
    ::= FunctionDecl
      | ClassDecl
      | InterfaceDecl
      | TraitDecl
      | EnumDecl
      | ConstDecl
      | VarDeclStmt ;

HaltCompilerStmt ::= "__halt_compiler" "(" ")" Term ;

(* ----------------------------------------------------------------- *
 *                            STATEMENTS                             *
 * ----------------------------------------------------------------- *)

Statement
    ::= EmptyStmt
      | ExpressionStmt
      | Block
      | IfStmt
      | WhileStmt
      | DoWhileStmt
      | ForStmt
      | ForeachStmt
      | SwitchStmt
      | TryStmt
      | ReturnStmt
      | BreakStmt
      | ContinueStmt
      | ThrowStmt
      | YieldStmt
      | GlobalStmt
      | StaticStmt
      | UnsetStmt
      | EchoStmt
      | PrintStmt
      | GotoStmt
      | LabelStmt
      | ExitStmt
      | IncludeStmt
      | RequireExpressionStmt
      | FunctionDecl
      | ClassLikeDecl
      | ConstDecl
      | DeclareStmt
      | VarDeclStmt ;

EmptyStmt ::= Term ;
ExpressionStmt ::= Expression Term ;
Block ::= "{" Statement* "}" ;

IfStmt
    ::= "if" "(" Expression ")" Statement
        ( "elseif" "(" Expression ")" Statement )*
        ( "else" Statement )? ;

WhileStmt ::= "while" "(" Expression ")" Statement ;
DoWhileStmt ::= "do" Statement "while" "(" Expression ")" Term ;

ForStmt ::= "for" "(" ForInit? ";" ForCondition? ";" ForUpdate? ")" Statement ;
ForInit ::= ExpressionList | VariableDeclarationList ;
ForCondition ::= ExpressionList ;
ForUpdate ::= ExpressionList ;

ForeachStmt ::= "foreach" "(" Expression "as" ForeachTarget ")" Statement ;
ForeachTarget
    ::= "&"? VariableName
      | "&"? VariableName "=>" "&"? VariableName ;

SwitchStmt ::= "switch" "(" Expression ")" "{" CaseClause* "}" ;
CaseClause
    ::= "case" Expression CaseSeparator Statement*
      | "default" CaseSeparator Statement* ;
CaseSeparator ::= ":" | ";" ;

TryStmt ::= "try" Block CatchClause* FinallyClause? ;
CatchClause ::= "catch" "(" CatchParameter ")" Block ;
CatchParameter ::= QualifiedNameList VariableName? ;
FinallyClause ::= "finally" Block ;

ReturnStmt ::= "return" Expression? Term ;
BreakStmt ::= "break" IntegerLiteral? Term ;
ContinueStmt ::= "continue" IntegerLiteral? Term ;
ThrowStmt ::= "throw" Expression Term ;
YieldStmt ::= Expression ;

GlobalStmt ::= "global" GlobalItem ( "," GlobalItem )* Term ;
GlobalItem ::= "&"? VariableName ;

StaticStmt ::= "static" StaticVariable ( "," StaticVariable )* Term ;
StaticVariable ::= VariableName ( "=" Expression )? ;

UnsetStmt ::= "unset" "(" UnsetItem ( "," UnsetItem )* ")" Term ;
UnsetItem ::= "&"? VariableName | ArrayAccess ;

EchoStmt ::= "echo" ExpressionList Term ;
PrintStmt ::= "print" Expression Term ;
GotoStmt ::= "goto" Identifier Term ;
LabelStmt ::= Identifier ":" ;
ExitStmt ::= ( "exit" | "die" ) ( "(" Expression? ")" | Expression )? Term ;

IncludeStmt ::= IncludeOperator Expression Term ;
IncludeOperator ::= "include" | "include_once" | "require" | "require_once" ;
RequireExpressionStmt ::= "require" Expression Term ;

(* ----------------------------------------------------------------- *
 *                            EXPRESSIONS                            *
 * ----------------------------------------------------------------- *)

Expression ::= YieldExpr ;

YieldExpr
    ::= "yield" "from" Expression
      | "yield" ( Expression ( "=>" Expression )? )?
      | AssignmentExpr ;

AssignmentExpr ::= TernaryExpr ( AssignmentOperator AssignmentExpr )? ;

AssignmentOperator
    ::= "=" | "+=" | "-=" | "*=" | "/=" | "%=" | "**=" | ".="
      | "&=" | "|=" | "^=" | "<<=" | ">>=" | "??=" ;

TernaryExpr ::= PipeExpr ( "?" Expression? ":" TernaryExpr )? ;

PipeExpr ::= NullCoalescingExpr ( "|>" NullCoalescingExpr )* ;

NullCoalescingExpr ::= LogicalOrExpr ( "??" LogicalOrExpr )* ;

LogicalOrExpr ::= LogicalXorExpr ( ( "||" | "or" ) LogicalXorExpr )* ;

LogicalXorExpr ::= LogicalAndExpr ( "xor" LogicalAndExpr )* ;

LogicalAndExpr ::= BitwiseOrExpr ( ( "&&" | "and" ) BitwiseOrExpr )* ;

BitwiseOrExpr ::= BitwiseXorExpr ( "|" BitwiseXorExpr )* ;

BitwiseXorExpr ::= BitwiseAndExpr ( "^" BitwiseAndExpr )* ;

BitwiseAndExpr ::= EqualityExpr ( "&" EqualityExpr )* ;

EqualityExpr
    ::= RelationalExpr ( ( "==" | "!=" | "===" | "!==" | "<>" | "<=>" ) RelationalExpr )* ;

RelationalExpr ::= ShiftExpr ( ( "<" | "<=" | ">" | ">=" ) ShiftExpr )* ;

ShiftExpr ::= AdditiveExpr ( ( "<<" | ">>" ) AdditiveExpr )* ;

AdditiveExpr ::= MultiplicativeExpr ( ( "+" | "-" | "." ) MultiplicativeExpr )* ;

MultiplicativeExpr ::= InstanceofExpr ( ( "*" | "/" | "%" ) InstanceofExpr )* ;

InstanceofExpr ::= UnaryExpr ( "instanceof" TypeReference )? ;

UnaryExpr
    ::= PrefixOperator UnaryExpr
      | CastExpr
      | ErrorSuppressExpr
      | "clone" UnaryExpr
      | ExponentExpr ;

PrefixOperator ::= "!" | "~" | "-" | "+" | "++" | "--" ;
ErrorSuppressExpr ::= "@" UnaryExpr ;

CastExpr ::= CastOperator UnaryExpr ;

CastOperator
    ::= "(" "int" ")"
      | "(" "float" ")"
      | "(" "string" ")"
      | "(" "array" ")"
      | "(" "object" ")"
      | "(" "bool" ")"
      | "(" "unset" ")"
      | "(" "mixed" ")"
      | "(" "resource" ")" ;

ExponentExpr ::= PostfixExpr ( "**" UnaryExpr )? ;

PostfixExpr ::= PrimaryExpr PostfixOperation* PostfixIncrementDecrement? ;

PostfixOperation
    ::= MemberAccess
      | NullsafeMemberAccess
      | StaticAccess
      | ArrayAccess
      | CallAccess
      | FirstClassCallable ;

MemberAccess ::= "->" MemberName ;
NullsafeMemberAccess ::= "?->" MemberName ;
StaticAccess ::= "::" StaticMemberName ;

MemberName ::= Identifier | VariableName | "{" Expression "}" ;
StaticMemberName ::= Identifier | VariableName | "{" Expression "}" ;

ArrayAccess ::= "[" Expression? "]" ;
CallAccess ::= "(" ArgumentList? ")" ;

FirstClassCallable
    ::= "->" MemberName "(...)"
      | "?->" MemberName "(...)"
      | "::" StaticMemberName "(...)" ;

PostfixIncrementDecrement ::= "++" | "--" ;

PrimaryExpr
    ::= VariableName
      | Literal
      | ArrayLiteral
      | ListExpression
      | ClassConstantFetch
      | StaticPropertyFetch
      | FunctionCall
      | MatchExpr
      | ClosureExpr
      | ArrowFunctionExpr
      | AnonymousClassExpr
      | NewExpr
      | ThrowExpr
      | IssetExpr
      | EmptyExpr
      | EvalExpr
      | ExitExpr
      | RequireExpr
      | PrintExpr
      | ParenthesizedExpr ;

FunctionCall ::= CallableName "(" ArgumentList? ")" ;
CallableName ::= QualifiedName | VariableName ;

ClassConstantFetch ::= TypeReference "::" ( Identifier | "class" ) ;
StaticPropertyFetch ::= TypeReference "::" VariableName ;

Literal
    ::= IntegerLiteral
      | FloatLiteral
      | StringLiteral
      | BooleanLiteral
      | NullLiteral
      | MagicConstant ;

ArrayLiteral ::= "[" ArrayElementList? "]" ;
ArrayElementList ::= ArrayElement ( Separator ArrayElement )* Separator? ;
ArrayElement
    ::= SpreadElement
      | Expression "=>" SpreadableExpression
      | Expression ;

SpreadableExpression ::= "..." Expression | Expression ;
SpreadElement ::= "..." Expression ;

ListExpression ::= "list" "(" ListItemList? ")" ;
ListItemList ::= ListItem ( Separator ListItem )* Separator? ;
ListItem
    ::= "&"? VariableName
      | "&"? ArrayAccess
      | SpreadElement
      | EmptyListItem ;

EmptyListItem ::= ;

MatchExpr ::= "match" "(" Expression ")" "{" MatchArmList? "}" ;
MatchArmList ::= MatchArm ( Separator MatchArm )* Separator? ;
MatchArm ::= MatchConditionList "=>" Expression ;
MatchConditionList ::= "default" | Expression ( "," Expression )* ;

ClosureExpr
    ::= "static"? "function" "&"? "(" ParameterList? ")"
        UseClause? ReturnTypeClause? Block ;

UseClause ::= "use" "(" ClosureUseList? ")" ;
ClosureUseList ::= ClosureUse ( "," ClosureUse )* ","? ;
ClosureUse ::= "&"? VariableName ;

ArrowFunctionExpr
    ::= "static"? "fn" "&"? "(" ParameterList? ")"
        ReturnTypeClause? "=>" Expression ;

AnonymousClassExpr ::= "new" "class" AnonymousClassHeader? Block ;
AnonymousClassHeader ::= "(" ParameterList? ")" ClassExtends? ClassImplements? ;

NewExpr ::= "new" NewTarget ( "(" ArgumentList? ")" )? ;
NewTarget
    ::= QualifiedName GenericArguments?
      | AnonymousClassExpr ;

ThrowExpr ::= "throw" Expression ;
IssetExpr ::= "isset" "(" IssetArgumentList? ")" ;
IssetArgumentList ::= IssetArgument ( "," IssetArgument )* ","? ;
IssetArgument ::= VariableName | ArrayAccess | MemberAccess ;

EmptyExpr ::= "empty" "(" Expression ")" ;
EvalExpr ::= "eval" "(" Expression ")" ;
ExitExpr ::= ( "exit" | "die" ) ( "(" Expression? ")" )? ;
RequireExpr ::= IncludeOperator Expression ;
PrintExpr ::= "print" Expression ;
ParenthesizedExpr ::= "(" Expression ")" ;

ArgumentList ::= Argument ( Separator Argument )* Separator? ;
Argument
    ::= NamedArgument
      | UnpackedArgument
      | Expression ;

NamedArgument ::= Identifier ":" Expression ;
UnpackedArgument ::= "..." Expression ;

ExpressionList ::= Expression ( "," Expression )* ","? ;

(* ----------------------------------------------------------------- *
 *                        OTY TYPE SYSTEM                            *
 * ----------------------------------------------------------------- *)

TypeExpr ::= ConditionalType ;

ConditionalType
    ::= UnionType ( "extends" TypeExpr "?" TypeExpr ":" TypeExpr )? ;

UnionType ::= IntersectionType ( "|" IntersectionType )* ;

IntersectionType ::= PostfixType ( "&" PostfixType )* ;

PostfixType ::= PrimaryType TypePostfix* ;

TypePostfix
    ::= GenericArguments
      | IndexedAccessTypeSuffix
      | ArrayTypeSuffix ;

GenericArguments ::= "<" TypeExprList ">" ;
IndexedAccessTypeSuffix ::= "[" TypeExpr "]" ;
ArrayTypeSuffix ::= "[" "]" ;

PrimaryType
    ::= PHPType
      | OtyType
      | "(" TypeExpr ")" ;

PHPType
    ::= PHPBuiltinType
      | PHPSpecialType
      | QualifiedName ;

PHPBuiltinType
    ::= "int"
      | "float"
      | "string"
      | "bool"
      | "array"
      | "object"
      | "callable"
      | "iterable"
      | "mixed"
      | "never"
      | "void"
      | "null"
      | "true"
      | "false"
      | "resource" ;

PHPSpecialType ::= "self" | "parent" | "static" ;

OtyType
    ::= LiteralType
      | TupleType
      | ArrayShapeType
      | StructTypeRef
      | TemplateLiteralType
      | KeyOfType
      | TypeOfType
      | InferType
      | MappedType
      | UtilityType ;

LiteralType
    ::= IntegerLiteral
      | FloatLiteral
      | StringLiteral
      | BooleanLiteral ;

TupleType ::= "[" TupleElementList? "]" ;
TupleElementList ::= TupleElement ( Separator TupleElement )* Separator? ;
TupleElement ::= ( Identifier ":" )? TypeExpr "?"? ;

ArrayShapeType ::= "array" "{" ShapeFieldList? "}" ;
ShapeFieldList ::= ShapeField ( Separator ShapeField )* Separator? ;
ShapeField ::= ShapeKey "?"? ":" TypeExpr ;
ShapeKey ::= Identifier | StringLiteral | IntegerLiteral ;

StructTypeRef ::= "struct" "{" StructFieldList? "}" ;
StructFieldList ::= StructFieldType ( Separator StructFieldType )* Separator? ;
StructFieldType ::= Identifier "?"? ":" TypeExpr ;

TemplateLiteralType ::= "`" TemplateComponent* "`" ;
TemplateComponent ::= TemplateText | "${" TypeExpr "}" ;

KeyOfType ::= "keyof" TypeExpr ;
TypeOfType ::= "typeof" ( QualifiedName | VariableName | RequireExpr ) ;
InferType ::= "infer" Identifier ;

MappedType
    ::= "{" "[" Identifier "in" TypeExpr ( "as" TypeExpr )? "]"
        MappedModifier* ":" TypeExpr "}" ;

MappedModifier
    ::= "+"? "readonly" | "-" "readonly"
      | "+"? "?" | "-" "?" ;

UtilityType
    ::= "Readonly" "<" TypeExpr ">"
      | "Partial" "<" TypeExpr ">"
      | "Required" "<" TypeExpr ">"
      | "Pick" "<" TypeExpr "," TypeExpr ">"
      | "Omit" "<" TypeExpr "," TypeExpr ">"
      | "Record" "<" TypeExpr "," TypeExpr ">"
      | "NonNullable" "<" TypeExpr ">"
      | "ReturnType" "<" TypeExpr ">"
      | "Parameters" "<" TypeExpr ">"
      | "Awaited" "<" TypeExpr ">"
      | "InstanceType" "<" TypeExpr ">" ;

TypeList ::= TypeExpr ( "," TypeExpr )* ","? ;
TypeExprList ::= TypeExpr ( "," TypeExpr )* ","? ;

TypeParameters ::= "<" TypeParameterList ">" ;
TypeParameterList ::= TypeParameter ( "," TypeParameter )* ","? ;
TypeParameter ::= Identifier ( "extends" TypeExpr )? ( "=" TypeExpr )? ;

ReturnTypeClause ::= ":" TypeExpr ;

TypeReference
    ::= QualifiedName GenericArguments?
      | "self"
      | "parent"
      | "static" ;

(* ----------------------------------------------------------------- *
 *                       ATTRIBUTES & STRUCTS                        *
 * ----------------------------------------------------------------- *)

Attribute ::= "#[" AttributeGroup "]" ;
Attributes ::= Attribute+ ;
AttributeGroup ::= AttributeItem ( Separator AttributeItem )* Separator? ;
AttributeItem ::= QualifiedName ( "(" ArgumentList? ")" )? ;

StructFieldDecl
    ::= Attributes? VisibilityModifier? "readonly"? TypeExpr VariableName ( "=" Expression )? Term ;

(* ----------------------------------------------------------------- *
 *                        LEXICAL STRUCTURE                          *
 * ----------------------------------------------------------------- *)

ScalarLiteral
    ::= IntegerLiteral
      | FloatLiteral
      | StringLiteral
      | BooleanLiteral ;

IntegerLiteral
    ::= DecimalInteger
      | HexInteger
      | BinaryInteger
      | OctalInteger ;

DecimalInteger ::= Digit ( Digit | "_" Digit )* ;
HexInteger ::= "0" ( "x" | "X" ) HexDigit ( HexDigit | "_" HexDigit )* ;
BinaryInteger ::= "0" ( "b" | "B" ) BinaryDigit ( BinaryDigit | "_" BinaryDigit )* ;
OctalInteger ::= "0" ( "o" | "O" ) OctalDigit ( OctalDigit | "_" OctalDigit )* ;

FloatLiteral
    ::= DecimalInteger "." DecimalDigits ExponentPart?
      | "." DecimalDigits ExponentPart?
      | DecimalInteger ExponentPart ;

ExponentPart ::= ( "e" | "E" ) ( "+" | "-" )? DecimalDigits ;
DecimalDigits ::= Digit ( Digit | "_" Digit )* ;

BooleanLiteral ::= "true" | "false" ;
NullLiteral ::= "null" ;

StringLiteral
    ::= SingleQuotedString
      | DoubleQuotedString
      | HeredocString
      | NowdocString ;

SingleQuotedString ::= "'" SingleQuotedCharacter* "'" ;
DoubleQuotedString ::= '"' DoubleQuotedCharacter* '"' ;

HeredocString ::= HeredocStart HeredocBody HeredocEnd ;
NowdocString ::= NowdocStart NowdocBody NowdocEnd ;

HeredocStart ::= "<<<" Identifier LineTerminator ;
NowdocStart ::= "<<<" "'" Identifier "'" LineTerminator ;

HeredocBody ::= HeredocCharacter* ;
NowdocBody ::= NowdocCharacter* ;

HeredocEnd ::= Identifier ";"? LineTerminator? ;
NowdocEnd ::= Identifier ";"? LineTerminator? ;

SingleQuotedCharacter ::= EscapeSequence | SourceCharacterExceptSingleQuote ;
DoubleQuotedCharacter ::= EscapeSequence | SourceCharacterExceptDoubleQuote ;

HeredocCharacter ::= SourceCharacter ;
NowdocCharacter ::= SourceCharacter ;

EscapeSequence
    ::= "\" ( "'" | '"' | "\" | "n" | "r" | "t" | "v" | "e" | "f"
            | "$" | "x" HexDigit HexDigit
            | "u" "{" UnicodeScalar "}" ) ;

UnicodeScalar ::= HexDigit HexDigit? HexDigit? HexDigit? HexDigit? HexDigit? ;

MagicConstant
    ::= "__LINE__"
      | "__FILE__"
      | "__DIR__"
      | "__FUNCTION__"
      | "__CLASS__"
      | "__TRAIT__"
      | "__METHOD__"
      | "__NAMESPACE__"
      | "__PROPERTY__"
      | "__COMPILER_HALT_OFFSET__" ;

VariableName ::= "$" Identifier | ImplicitItVariable ;
ImplicitItVariable ::= "$it" ;

QualifiedName ::= "\\"? Identifier ( "\\" Identifier )* ;

Identifier ::= IdentifierStart IdentifierPart* ;
IdentifierStart ::= Letter | "_" | ExtendedIdentifierStart ;
IdentifierPart ::= IdentifierStart | Digit ;
ExtendedIdentifierStart ::= UnicodeIdentifierStart ;

Letter ::= "A".."Z" | "a".."z" ;
Digit ::= "0".."9" ;
HexDigit ::= Digit | "A".."F" | "a".."f" ;
BinaryDigit ::= "0" | "1" ;
OctalDigit ::= "0".."7" ;

Separator ::= "," | NEWLINE | "," NEWLINE ;
Term ::= ";" | NEWLINE ;

Shebang ::= "#!" ShebangText LineTerminator ;

NEWLINE ::= LineTerminator ;
LineTerminator ::= "\r\n" | "\r" | "\n" ;
Whitespace ::= ( " " | "\t" | "\v" | "\f" )+ ;

LineComment ::= "//" CommentText | "#" CommentText ;
BlockComment ::= "/*" BlockCommentText "*/" ;
Comment ::= LineComment | BlockComment ;

CommentText ::= SourceCharacterExceptLineTerminator* ;
BlockCommentText ::= SourceCharacterExceptBlockCommentEnd* ;

SourceCharacter ::= #x0000..#x10FFFF ;
SourceCharacterExceptSingleQuote ::= SourceCharacter - "'" ;
SourceCharacterExceptDoubleQuote ::= SourceCharacter - '"' ;
SourceCharacterExceptLineTerminator ::= SourceCharacter - "\r" - "\n" ;
SourceCharacterExceptBlockCommentEnd ::= SourceCharacter ;

TemplateText ::= TemplateCharacter+ ;
TemplateCharacter ::= SourceCharacter - "`" - "$" ;

EOF ::= ;
